// <auto-generated />
namespace WixServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class grid_size : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grid_size));
        
        string IMigrationMetadata.Id
        {
            get { return "201604201614014_grid_size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
