// <auto-generated />
namespace WixServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_photo_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_photo_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201606140932514_add_photo_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
